# Generated by Django 5.1.6 on 2025-02-25 09:02

import django.db.models.deletion
import fraud.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_number', models.CharField(max_length=20, unique=True)),
                ('expiry_date', models.DateField()),
                ('cvv', models.IntegerField()),
                ('card_type', models.CharField(max_length=20)),
                ('credit_limit', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('is_active', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('merchant_name', models.CharField(max_length=255)),
                ('merchant_category', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='fraud.card')),
            ],
        ),
        migrations.CreateModel(
            name='IsFraud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_fraud', models.BooleanField(default=False)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fraud.transaction')),
            ],
        ),

        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cards', to='fraud.user'),
        ),
    ]
