# Generated by Django 5.1.6 on 2025-02-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isfraud',
            name='is_fraud',
            field=models.IntegerField(default=0),
        ),
    ]
