# Generated by Django 5.1.6 on 2025-03-04 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0002_alter_isfraud_is_fraud'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudAlerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_score', models.FloatField()),
                ('threshold', models.FloatField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('alert_sent', models.BooleanField(default=False)),
                ('sent_timestamp', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud', to='fraud.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='FraudAlertEmails',
            fields=[
                ('email_id', models.AutoField(primary_key=True, serialize=False)),
                ('email_subject', models.CharField(max_length=255)),
                ('email_body', models.TextField()),
                ('sent_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_emails', to='fraud.user')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_alerts', to='fraud.fraudalerts')),
            ],
        ),
    ]
