# Generated by Django 5.1.6 on 2025-03-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0003_fraudalerts_fraudalertemails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraudalerts',
            name='sent_timestamp',
            field=models.DateField(blank=True, null=True),
        ),
    ]
